# Generated by Django 5.1.6 on 2025-02-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Meta",
            new_name="Item",
        ),
    ]
