# Generated by Django 5.1.6 on 2025-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_rename_meta_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://i0.wp.com/stewwithsaba.com/wp-content/uploads/2024/02/IMG_3902-edited.jpg?resize=900%2C1200&ssl=1",
                max_length=150,
            ),
        ),
    ]
