# Generated by Django 5.1.6 on 2025-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
