# Generated by Django 5.1.4 on 2024-12-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.IntegerField()),
                ("login_time", models.CharField(max_length=10)),
                ("logout_time", models.CharField(max_length=10)),
            ],
        ),
    ]
