# Generated by Django 5.1.6 on 2025-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("summary", models.TextField(max_length=2200)),
                ("degree", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("previous_work", models.TextField(max_length=1000)),
                ("skills", models.TextField(max_length=1000)),
            ],
        ),
    ]
