# Generated by Django 5.1.6 on 2025-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("date_issued", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=100)),
                ("board", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=100)),
                ("responsibilities", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("technologies", models.CharField(max_length=500)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="previous_work",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="school",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="university",
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="certifications",
            field=models.ManyToManyField(blank=True, to="pdf.certification"),
        ),
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.ManyToManyField(blank=True, to="pdf.education"),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.ManyToManyField(blank=True, to="pdf.experience"),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects",
            field=models.ManyToManyField(blank=True, to="pdf.project"),
        ),
    ]
